### ISSUE TITLE
'Content-Encoding': 'gzip' is added to headers regardless of opts config

### ISSUE THREAD

**Issue by mooeypoo** [kartotherian/babel#1]
This is visible through the failing unit tests; the headers get `'Content-Encoding': 'gzip'` regardless of the `gzip` option that's passed. 

I've tried to follow the route of the code through but it seems like somewhere in the stack when we unpack the tile and repack it, the `'Content-Encoding': 'gzip'` is added indiscriminately.

@nyurik is this a known issue that we should fix in the code, or is this a bad expectation of the unit tests?

If the tests are correct in expecting `'Content-Encoding': 'gzip'` only when requested, can you point me towards where? I've went into @kartotherian/core down the rabbit hole, and am still not sure what adds it in, and I have a sense this isn't even in babel. If that's the case, maybe the tests should be corrected?

**Comment by nyurik** [comment]
This is a weird expectation of the stack.  Tilelive components hardcode this behavior, and it would be fairly tricky to get rid of it. Basically the whole stack expects tiles to be gziped.

There were some attempts to clean it up, e.g.  https://github.com/mojodna/tilelive-http/issues/17 and https://github.com/mojodna/tilelive-http/pull/18 for the tilelive-http

**Comment by nyurik** [comment]
There is a good discussion about it at https://github.com/mapbox/vector-tile-spec/issues/27

**Comment by mooeypoo** [comment]
If that's the case, should we change the tests to not expect this outcome? I don't want to cancel this behavior if we **do** need to expect it, but if this is so deeply expected in the stack, the tests will be useless otherwise...? We should have them test, as much as possible, the distinct behavior of the specific package. This will be a challenge when it's touching so many others, but at least we can attempt to not rely on expectations it doesn't control?

**Comment by nyurik** [comment]
fixed, i think it was my mistake in the tests. Reopen if you think we should further work on it.
